AshAvalanche/ansible-avalanche-collection

- playbooks/add_validator.yml
- playbooks/create_admin_user.yml
- roles/node/defaults/main.yml
- roles/node/tasks/add-validator.yml
- roles/node/tasks/admin-user.yml
**Note**: The funding of the created P-chain address created for the `admin` user must be done manually between calling `playbooks/create_admin_user.yml` and `playbooks/add_validator.yml`.
I'm not sure if we should invest time in automating this now.
> feat: add user and add validator tasks

- .gitignore
- README.md
- plugins/filter/README.md
- plugins/filter/convert.py
- roles/node/defaults/main.yml
This PR adds a new filter to the collection to easily convert between AVAX units. E.g.:
```yml
amount: "{{ 25 | ash.avalanche.convert('AVAX', 'nAVAX') | int }}"
```
> feat: add convert ansible filter

- roles/node/tasks/install-avalanchego.yml
> fix: remove duplicate plugins dir creation

- roles/node/tasks/clean-plugins-dir.yml
- roles/node/tasks/main.yml
Fix #27 
Added a `clean-plugins-dir.yml` task triggered when `avalanchego_vms_install` is empty.
> fix: clean plugins dir if avalanchego_vms_install is empty

- galaxy.yml
- roles/blockchain/defaults/main.yml
- roles/node/README.md
- roles/node/defaults/main.yml
- roles/node/tasks/bootstrap-db.yml
- roles/node/tasks/clean-plugins-dir.yml
- roles/node/tasks/config-chains.yml
- roles/node/tasks/config-node.yml
- roles/node/tasks/config-subnets.yml
- roles/node/tasks/install-avalanchego.yml
- roles/node/tasks/install-vm.yml
- roles/node/vars/main.yml
- scripts/update_vm_versions.py
- Fixes #32 
- Use releases from Ava Labs repository instead of our own
- Change the default VM for creating a blockchain to Subnet EVM
- Add the possibility to customize the AvalancheGo user group
- Bump collection version to `0.5.1`
> Use Ava Labs VM releases

- galaxy.yml
- playbooks/bootstrap_local_network.yml
- playbooks/provision_nodes.yml
- roles/ash_cli/defaults/main.yml
- roles/ash_cli/tasks/install.yml
- roles/ash_cli/tasks/main.yml
- roles/ash_cli/vars/main.yml
- roles/blockscout/tasks/config-blockscout.yml
- roles/faucet/tasks/install-faucet.yml
- roles/node/tasks/config-chains.yml
- roles/node/tasks/install-avalanchego.yml
None
- Add the `ash_cli` role that installs the Ash CLI from [ash-rs](https://github.com/AshAvalanche/ash-rs) releases
In the future, this role could also template Ash configuration files depending on the network.
> feat: add ash_cli role

- roles/ash_cli/defaults/main.yml
- roles/ash_cli/tasks/config.yml
- roles/ash_cli/tasks/install.yml
- roles/ash_cli/tasks/main.yml
- roles/ash_cli/templates/ash-command.j2
- roles/ash_cli/vars/main.yml
- Fixes #53 
- https://github.com/AshAvalanche/ash-rs/pull/35
- Add the `config` playbook to the `ash_cli` role. This allows defining a default configuration through environment variables, especially for local networks that have a changing P-Chain endpoint
Note that the `--config` argument takes preference over the configuration provided through env variables.
> feat(ash_cli): add config playbook

- files/dashboards/c_chain.json
- files/dashboards/database.json
- files/dashboards/machine.json
- files/dashboards/main.json
- files/dashboards/network.json
- files/dashboards/p_chain.json
- files/dashboards/x_chain.json
- playbooks/install_monitoring_stack.yml
- requirements.yml
- Fix #51 
- Added the `ash.avalanche.install_monitoring_stack` playbook to install Prometheus, Prometheus Node Exporter and Grafana
- Added the Prometheus collection and Grafana role in `requirements.txt`
Dashboards come from https://github.com/ava-labs/avalanche-monitoring, I opened https://github.com/ava-labs/avalanche-monitoring/pull/8 to fix some light issues.
The Subnets dashboard will require templating so I saved it for later.
When running the `ash.avalanche.install_monitoring_stack` playbook from the `ansible-avalanche-getting-started` env, the following warnings can be seen:
```
[WARNING]: Collection prometheus.prometheus does not support Ansible version 2.14.3
```
- [docs](https://prometheus-community.github.io/ansible/branch/main/) state `~= 2.14.0` so we should be good.
``` …
```
> feat: monitoring stack

- roles/node/defaults/main.yml
- Fix #72 
- Removed deprecated `snow-mixed-query-num-push-vdr` config key
- Added the `http-allowed-hosts` config key and var
> feat: adapt config to v1.10.3

- roles/node/tasks/config-node.yml
- Fix #76 
- Switched `avalanchego_node_json` in the `combine` filter to let the already defined keys keep their values
> feat: avalanchego_node_json precedence in combine

- plugins/modules/ash_cmd.py
- roles/node/defaults/main.yml
- roles/node/tasks/add-validator.yml
- Fixes #80
- `avalanche.node`
- Rename validator vars in the `node` role to avoid overlapping with var names in the `subnet` role
- Explicitly pass vars in the `include_role` task
- `avalanche.ash_cmd`
- Directly call the Ash CLI binary instead of the script in `/bin/local`. This is to avoid conflicts in env vars
- Add the `ash_config` argument
> Fix add-validator vars propagation

- playbooks/bootstrap_local_network.yml
- requirements.yml
- roles/ash_cli/tasks/main.yml
- roles/node/defaults/main.yml
- roles/node/tasks/config-node.yml
- roles/node/tasks/install-vms.yml
- roles/node/tasks/main.yml
- Fixes #83 
- `avalanche.node`
- Allow to specify multiple bootstrap nodes on networks other than `mainnet` or `fuji`
- Use `import_tasks` instead of `include_tasks` in the main playbook. This allows propagating tags to all included tasks.
- Add tags on all `import_tasks` in the main playbook
- `avalanche.node`
- `bootstrap_node` group renamed to `bootstrap_nodes`
- `avalanchego_bootstrap_node_id` var renamed to `avalanchego_bootstrap_node_ids`
> Add Ansible tags + allow multiple bootstrap nodes

- roles/ash_cli/tasks/config.yml
- Fix #85 
- Add conditional check to `ash_cli_custom_networks` before config loop
> feat: verify ash_cli_custom_networks is defined

- roles/node/defaults/main.yml
- roles/node/tasks/add-validator.yml
- roles/subnet/defaults/main.yml
- roles/subnet/tasks/add-validator.yml
- Fix #92 
- Introduced `validator_command_os_family` with default value `Debian`
- Removed `subnet_validator_*_time_*` vars and replaced with hardcoded timestamps in the example. Makes more sense IMO since it's there to showcase how to define specific weight, times, etc. for each nodes. Will update the docs accordingly if you agree.
> fix: register ansible's localhost for date command

- roles/ash_cli/tasks/install.yml
- roles/ash_cli/vars/main.yml
- roles/node/tasks/install-avalanchego.yml
- roles/node/vars/main.yml
- Fix #96 
- Introduced vars `ash_cli_binary_arch` and `avalanchego_binary_arch`
- Added a task to resolve above vars depending on the target machine architecture
> feat: support arm64 arch

- roles/node/tasks/config-node.yml
- roles/node/tasks/install-vm.yml
- roles/node/vars/main.yml
- Fixes #98 
- Fixes #100 
- `ash.avalanche.node`
- Download the VM binary based on the host arch
- Upload staking TLS cert + key as `node.(cert|key)`
> fix: VM binary arch

- roles/node/defaults/main.yml
- Create the `avalanche` parent directory in `/var/lib` to enable storing data from other Avalanche software
> feat(node): create a parent directory in /var/lib

- roles/node/defaults/main.yml
- roles/node/tasks/config-node.yml
- Add `testnet` as a known public network (where bootstrap nodes are not needed). See [Network ID](https://docs.avax.network/nodes/configure/avalanchego-config-flags#network-id)
> fix(node): add 'testnet' as a public networks

- roles/node/tasks/main.yml
- Fixes #104 
- Add a default value for `ash_cli_networks` (useful for networks other than `local`)
> fix(node): default value for ash_cli_networks

- roles/ash_cli/defaults/main.yml
- roles/ash_cli/tasks/install.yml
None
None
- added owner and group parameters to defaults 
- updated role to use the new owner and group parameters
- default values for both are root as before
None
None
> parametrized the owner and group for ash_cli

- roles/node/defaults/main.yml
- roles/node/tasks/clean-plugins-dir.yml
- roles/node/tasks/config-node.yml
- roles/node/tasks/install-vm.yml
- roles/node/vars/main.yml
- Fixes #106 
- `avalanche.node` role
- Remove the usage of VM aliases and use the VM ID as the name for the symlink to the VM binary
- Decorrelate the VM name (in the collection conf) and the binary filename (to be downloaded + extracted). This allows installing the same VM multiple times with different VM IDs.
You can test this by installing the Subnet EVM with the default ID + the Subnet VM with a different ID and creating a Subnet using the 2 VMs for 2 blockchains.
In `ansible-avalanche-getting-started`:
```yaml
avalanchego_vms_list:
dexalot-subnet-evm:
download_url: https://github.com/ava-labs/subnet-evm/releases/download
id: mDVSxzeWHpEU3eSqMwwGQsD787xGp7hv9Qgoe3R9SdjPapte8
ash_vm_type: SubnetEVM
binary_filename: subnet-evm
versions_comp:
0.5.9:
ge: 1.10.15
le: 1.10.17
0.5.10:
ge: …
```
> feat(node): use VM ID for symlinks to VM binary

- roles/subnet/defaults/main.yml
- Fix #111 
- Comment `subnet_blockchains_list` to make it an example
- We should be fine since we already define `subnet_blockchains_list` in the `ansible-avalanche-getting-started` inventory
> feat: comment subnet_blockchains_list

- roles/node/defaults/main.yml
- roles/node/tasks/clean-plugins-dir.yml
- roles/node/tasks/install-vms.yml
- roles/node/templates/vm-aliases.json.j2
- Fixes #113 
- `avalanche.node`
- Change `avalanchego_vms_install` to a dictionary to ease merging multi-file configurations.
To migrate, one has to change the list of VMs to install. E.g.
```yaml
avalanchego_vms_install:
- subnet-evm=0.5.10
avalanchego_vms_install:
subnet-evm: 0.5.10
```
> feat(node): use a dict for avalanchego_vms_install

- roles/node/defaults/main.yml
- roles/node/tasks/health-checks.yml
- roles/node/tasks/main.yml
- Fixes #115 
None
This PR adds a new variable ash_cli_network_id to the node defaults/main.yml and uses it in health_checks and main tasks of the node role.  It allows the ash_cli and avalanchego to have different network ids.
None
None
> fix to allow different network ids between ash_cli and avalanchego

- roles/ash_cli/defaults/main.yml
- roles/node/tasks/add-validator.yml
- roles/subnet/tasks/add-validator.yml
- Fixes #120 
- https://github.com/AshAvalanche/ash-rs/pull/90
- Resolve node signer (BLS public key + PoP) before adding a validator in `avalanche.node.add-validator`
- Provide the node signer when adding a validator to the Primary Network in `avalanche.subnet.add-validator`
The node signer is automatically resolved through `ash avalanche node info`.
> feat: provide node signer when adding as validator

- roles/node/tasks/install-vm.yml
- Fix #125 
- Allow the use of a `path` variable to upload the VM binary from a local file instead of fetching a GitHub release. Will be useful for debugging.
Example:
```yml
avalanchego_vms_list:
tokenvm:
path: "{{ inventory_dir }}/../../files" # tokenvm_0.0.999_linux_amd64.tar.gz
id: tHBYNu8ikqo4MWMHehC9iKB9mR5tB3DWzbkYmTfe9buWQ5GZ8
ash_vm_type: Custom
binary_filename: tokenvm
aliases:
- tokenvm
versions_comp:
0.0.999:
ge: 1.10.10
le: 1.10.10
```
> feat: allow a path variable for local VM archive fetching

- plugins/modules/vm_version_compat.py
- roles/node/defaults/main.yml
- roles/node/tasks/install-vm.yml
- roles/node/vars/main.yml
- scripts/update_vm_versions.py
- Fixes #128 
- Fixes #127 
- Add the `vm_version_compat` module that dynamically checks that an Avalanche VM version is compatible with an AvalancheGo version. It uses `compatibility.json` files to do so
- Use `vm_version_compat` by default for VM compatibility check. The existing behavior is still supported.
The compatibility files are expected at the root of the VM repo (e.g. [subnet-evm](https://github.com/ava-labs/subnet-evm/blob/master/compatibility.json)) and in the [version/](https://github.com/ava-labs/avalanchego/blob/master/version/compatibility.json) folder of AvalancheGo.
> feat: add + use vm_version_compat module

- playbooks/install_blockscout_docker.yml
- roles/evm/blockscout/defaults/main.yml
- roles/evm/blockscout/handlers/main.yml
- roles/evm/blockscout/tasks/main.yml
- Add install, configure and start tags on Blockscout playbook.
- Add env var execution condition on restart handler as tags isn't applied on it:
ansible-playbook ash.avalanche.install_blockscout_docker -i inventories/local -t "config" -e skip_handlers=true
> fix(blockscout): add tags on playbook
